[workspace]
members = ["baldr", "mimir", "tyr", "vidar"]

[replace]
"derive_builder:0.5.0" = { path = "../rust-derive-builder/derive_builder" }
"mimir:0.2.0" = { path = "mimir" }
"vidar:0.1.0" = { path = "vidar" }
